services:
  - type: web
    name: GURU-MD
    env: node
    plan: free
    repo: https://github.com/itsguruu/GURU
    branch: main
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    envVars:
      - key: SESSION_ID
        sync: false  # Don't include the value here, will be entered manually on Render
      - key: OWNER_NUMBER
        sync: false
        value: "254778074353"  # ‚Üê Your updated owner number
